config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'products#index'
  resources :products, only: %i[index show]

  resource :cart, only: %i[show update destroy]

  post 'add_to_cart/:product_id', to: 'carts#add_item', as: 'add_to_cart'

  resources :orders, only: %i[index new create] do
    member do
      get 'order_confirmation', to: 'orders#order_confirmation'
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart_item.rb
# frozen_string_literal: true

class CartItem < ApplicationRecord
  belongs_to :product
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  has_many :cart_items
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :initialize_cart

  private

  def initialize_cart
    @cart = Cart.new(session[:cart] ||= {})
  end
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  def show
    @cart_items = CartItem.all
  end

  def update
    item = CartItem.find_by(id: params[:cart_item][:id])
    item.update(quantity: params[:cart_item][:quantity].to_i)
    redirect_to cart_path
  end

  def destroy
    item = CartItem.find_by(id: params[:id])
    item.destroy
    redirect_to products_path
  end

  def add_item
    product = Product.find(params[:product_id])
    @cart_item = CartItem.find_by(product_id: product.id)

    if @cart_item
      @cart_item.quantity = @cart_item.quantity.nil? ? 1 : @cart_item.quantity + 1
    else
      @cart_item = CartItem.create(product:, quantity: 1)
    end

    if @cart_item.save
      flash[:success] = 'Item added to cart'
    else
      flash[:error] = 'Item not added to cart'
    end

    redirect_to cart_path(product)
  end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    @order.bill = CartItem.all.sum { |item| item.product.price * item.quantity }
    if @order.save
      CartItem.destroy_all
      redirect_to order_confirmation_order_path(@order)
    else
      render :new
    end
  end

  def order_confirmation
    @order = Order.find(params[:id])
  end

  private

  def order_params
    params.require(:order).permit(:customer_name, :shipping_address, :phone_number, :payment_method)
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :set_product, only: %i[show]

  def index
    @products = Product.all
  end

  def show
    @cart_item = CartItem.new
    @cart_item.product = @product
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/carts/show.html.erb
<h1>Shopping Cart</h1>
<% if @cart_items.any? %>

  <ul>
    <% @cart_items.each do |item| %>
      <li>
        <div class="item-info">
          <div class="item-name"><%= item.product.name %></div>
          <%= form_for item, url: cart_path, method: :put, class: "item-form" do |f| %>
            <%= f.number_field :quantity, value: item.quantity, min: 1, class: "quantity-field" %>
            <%= f.hidden_field :id, value: item.id %>
            <%= f.submit "+", class: "plus-button" %>
            <%= f.submit "-", class: "minus-button" %>
          <% end %>
        </div>
        <div class="item-price"><%= number_to_currency(item.product.price * item.quantity) %></div>
        <%= button_to 'Remove from Cart', cart_path(id: item.id), method: :delete %>
      </li>
    <% end %>
  </ul>
  <div class="confirm-order-container">
    <%= link_to 'Confirm Order', new_order_path, class: "confirm-order-button" %>
  </div>
<% else %>
  <p>Please add items to your cart!</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShoppingProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <nav>
      <%= link_to 'Cart', cart_path, class: 'cart-button' %></li>
      <%= link_to 'Products List', products_path, class: 'cart-button' %>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/orders/index.html.erb
<h1>Order History</h1>

<% if @orders.any? %>
  <table>
    <thead>
      <tr>
        <th>Order Number</th>
        <th>Customer Name</th>
        <th>Shipping Address</th>
        <th>Phone Number</th>
        <th>Payment Method</th>
        <th>Total Amount</th>
        <th>Order Date</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= order.id %></td>
          <td><%= order.customer_name %></td>
          <td><%= order.shipping_address %></td>
          <td><%= order.phone_number %></td>
          <td><%= order.payment_method %></td>
          <td><%= number_to_currency(order.bill) %></td>
          <td><%= order.created_at.strftime('%b %d, %Y') %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No orders found.</p>
<% end %>

app/views/orders/new.html.erb
<div class="d-flex items-center justify-content-center h-screen">
  <div class="w-full max-w-md">
    <h2 class="text-center text-2xl font-bold mb-4">Add details to place your Order</h2>
    <%= form_for @order do |f| %>
      <div style="margin-bottom: 5px;">
        <%= f.label :customer_name, class: "block text-gray-700 font-bold mb-2" %>
        <%= f.text_field :customer_name, placeholder: "Enter your name", class: "form-input block w-full" %>
      </div>

      <div style="margin-bottom: 5px;">
        <%= f.label :shipping_address, class: "block text-gray-700 font-bold mb-2" %>
        <%= f.text_area :shipping_address, placeholder: "Enter your address", class: "form-textarea block w-full" %>
      </div>

      <div style="margin-bottom: 5px;">
        <%= f.label :phone_number, class: "block text-gray-700 font-bold mb-2" %>
        <%= f.text_field :phone_number, placeholder: "Enter your phone number", class: "form-input block w-full" %>
      </div>

      <div style="margin-bottom: 5px;">
        <%= f.label :payment_method, class: "block text-gray-700 font-bold mb-2" %>
       <%= f.select :payment_method, options_for_select([["Credit Card", "credit_card"], ["PayPal", "paypal"], ["Apple Pay", "apple_pay"], ["Google Pay", "google_pay"], ["Venmo", "venmo"]]), {}, { class: "form-select block w-full" } %>

      </div>

      <%= f.submit "Place Order", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded block mx-auto" %>
    <% end %>
  </div>
</div>

app/views/orders/order_confirmation.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Order Complete</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      font-size: 16px;
      line-height: 1.5;
      color: #333;
      margin: 0;
      padding: 0;
    }
    
    .container {
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
    }
    
    h1 {
      font-size: 36px;
      font-weight: bold;
      margin-bottom: 20px;
    }
    
    p {
      margin-bottom: 10px;
    }
    
    .order-details {
      border: 1px solid #ccc;
      padding: 20px;
      margin-bottom: 20px;
    }
    
    .order-details p {
      margin: 0;
    }
    
    .total-price {
      font-size: 24px;
      font-weight: bold;
      margin-top: 20px;
      margin-bottom: 10px;
    }
    
    a {
      color: #06c;
      text-decoration: none;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>Order Complete</h1>
    
    <p>Thank you for your order!</p>

    <div class="order-details">
      <p>Order Details:</p>
      <p>Name: <%= @order.customer_name %></p>
      <p>Shipping Address: <%= @order.shipping_address %></p>
      <p>Phone Number: <%= @order.phone_number %></p>
      <p>Payment Method: <%= @order.payment_method %></p>
    </div>

    <p class="total-price">Total Price: <%= number_to_currency(@order.bill || 0) %></p>
    
    <p><%= link_to 'Orders History', orders_path %></p>
  </div>
</body>
</html>

app/views/products/index.html.erb
<h1 class="title">Products</h1>

<div class="product-list">
  <% @products.each do |product| %>
    <div class="product-item">
    <% if product.image.present? %>
      <%= image_tag product.image, class: "product-image" %>
    <% end %>
      <h2><%= product.name %></h2>
      <p class="description"><%= product.description %></p>
      <p class="price"><%= number_to_currency(product.price) %></p>
      <%= link_to 'View Details', product_path(product), class: "button" %>
    </div>
  <% end %>
</div>

app/views/products/show.html.erb
<div class="container">
  <h1><%= @product.name %></h1>
  <p><%= @product.description %></p>
  <p><%= number_to_currency(@product.price) %></p>
  <% if @product.image.present? %>
    <%= image_tag @product.image, style: 'max-width: 50%;' %>
  <% end %>
  <div style="position: absolute; top: 50%; right: 0; transform: translate(0, -50%);">
  <%= form_for @cart_item, url: add_to_cart_path(@product.id), style: 'display: inline-block;' do |f| %>
    <%= f.submit 'Add to Cart' %>
  <% end %>
</div>

</div>